### ISSUE TITLE
problem on get_attribute function

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#101]
Following is a simplified version of an ETSI NFV SOL001 example:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  tosca.nodes.nfv.VNF:
    attributes:
      scale_status:
        type: map
        entry_schema:
          type: integer
  MyCompany.SunshineDB.1_0.1_0:
    derived_from: tosca.nodes.nfv.VNF
    attributes:
      call_proc_scale_level:
        type: integer
topology_template:
  node_templates:
    SunshineDB:
      type: MyCompany.SunshineDB.1_0.1_0
      attributes:
        call_proc_scale_level: { get_attribute: [ SELF, scale_status, call_proc ] }
```

Compiling this template with puccini 0.21.1 produces a problem:

```sh
$ puccini-tosca compile --coerce example.yaml 
PROBLEMS (1)
  file:/.../example.yaml 
    @20,9 topology_template.node_templates["SunshineDB"].attributes["call_proc_scale_level"]: call to tosca.function.get_attribute("SELF","scale_status","call_proc") failed because nested attribute "scale_status.call_proc" not found in "SunshineDB"
```
`scale_status` is a declared attribute of `SunshineDB` node template, and is a map with string keys and integer entries.

Until the execution, it is impossible to check that the `scale_status` map contains the `call_proc` key.

But a TOSCA parser should only check that `call_proc` is of type string (else this is a typing error) and that the type of the get_attribute expression (here `integer`) is compatible with the type of the assigned attribute (here `integer`), else this is a typing error. So we could expect that this template should not be rejected by any TOSCA parser/compiler.

Am I missing something on this example?
