### ISSUE TITLE
single-line grammar for repositories unsupported

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#103]
For the following service template
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
repositories:
  docker_hub: https://registry.hub.docker.com/
  another_repository:
    url: https://registry.hub.docker.com/
```
puccini raises the following errors
```sh
$ puccini-tosca puccini-tosca-repositories-single-line-grammar.yaml 
PROBLEMS (2)
  file:/.../puccini-tosca-repositories-single-line-grammar.yaml
    @3,3 repositories["docker_hub"]: "string" instead of "map"
    @3,3 repositories["docker_hub"].url: missing required field
```
The multi-line grammar for repositories is supported but the single-line grammar for repositories seems to not be supported.
