### ISSUE TITLE
 Incorrect Type URI for BlockStorage node type

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#105]
For the following service template
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    storage1:
      type: BlockStorage # Shorthand Name
      properties:
        name: storage1
    storage2:
      type: tosca.nodes.Storage.BlockStorage # Correct Type URI
      properties:
        name: storage2
    storage3:
      type: tosca.nodes.BlockStorage # Undefined Type URI!
      properties:
        name: storage3
```
puccini raises an error
```sh
$ puccini-tosca puccini-blockstorage.yaml 
PROBLEMS (1)
  file:/.../puccini-blockstorage.yaml
    @10,7 topology_template.node_templates["storage2"].type: reference to unknown node type: tosca.nodes.Storage.BlockStorage
```

According to Section 5.9.11 of TOSCA 1.3, `tosca.nodes.Storage.BlockStorage` is a correct Type URI.
`tosca.nodes.BlockStorage` is not defined in TOSCA 1.3.

The issue seems to come from https://github.com/tliron/puccini/blob/main/assets/tosca/profiles/simple/1.3/nodes.yaml.
`tosca.nodes.BlockStorage` shall be replaced by `tosca.nodes.Storage.BlockStorage`.
Note that `tosca.nodes.ObjectStorage` shall be replaced by `tosca.nodes.Storage.ObjectStorage` according to Section 5.9.10 of TOSCA 1.3.
