### ISSUE TITLE
outputs without type field

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#106]
For the following service template
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    compute:
      type: tosca.nodes.Compute
      attributes:
        public_address: my.compute.com
  outputs:
    compute_public_address:
      value: { get_attribute: [compute, public_address] }
```
puccini reports the following error

```sh
$ puccini-tosca parse puccini-output_without_type.yaml 
PROBLEMS (1)
  file:/.../puccini-output_without_type.yaml
    @10,5 topology_template.outputs["compute_public_address"].type: missing required field
```

According to Section 3.6.14.1 of TOSCA 1.3 or Section 4.4.11.1 of TOSCA 2.0, the `type` keyname is not required/mandatory.
For info, this template is validated by Ubicity Validator, xOpera and my own parser.
