### ISSUE TITLE
Attribute defaults are broken for list types

### ISSUE THREAD

**Issue by tliron** [tliron/puccini#108]
```yaml
tosca_definitions_version: tosca_2_0

node_types:

  Hello:
    attributes:
      hello:
        type: list
        entry_schema: string
        default: [ hi ]

topology_template:

  node_templates:

    hello:
      type: Hello
```
Will lead to this problem:
```
@10,9 node_types["Hello"].attributes["hello"].default: "*tosca_v2_0.ValueList" instead of "list"
```
There is no problem if `attributes` is changed to `properties`.
