### ISSUE TITLE
Keywords TARGET and SOURCE are not supported in output mapping

### ISSUE THREAD

**Issue by Shishqa** [tliron/puccini#121]
## Example

Let's consider an example, where I want to change some attributes through a relationship:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

relationship_types:

  CustomDependsOn:
    derived_from: tosca.relationships.DependsOn
    interfaces:
      Configure:
        operations:
          configure:
            implementation: playbook.yaml
            outputs:
              var: [ TARGET, tosca_id ]

topology_template:

  node_templates:

    node_2:
      type: tosca:Root
      requirements:
        - dependency:
            node: node_1
            relationship:
              type: CustomDependsOn

    node_1:
      type: tosca:Root
```

The puccini gives a parsing error:
```
PROBLEMS (1)
  file:/home/shishqa/dev/tmp/puccini/example.yaml
    @13,22 relationship_types["CustomDependsOn"].interfaces["Configure"].operations["configure"].outputs["var"][0]: unknown node template: TARGET
```

> Puccini was built from latest commit f8c4d215ac1c75eb0645771425af60ff711909ad

### Expected

As TARGET and SOURCE are known when parsing the template, puccini can set a `nodeTemplateName` to the exact node bound to the relationship

### Details

For now, puccini can parse such an example:

```
tosca_definitions_version: tosca_simple_yaml_1_3

topology_template:

  node_templates:

    node_2:
      type: tosca:Compute
      interfaces:
        Standard:
          operations:
            configure:
              implementation: playbook.yaml
              outputs:
                var: [ node_1, tosca_id ]

    node_1:
      type: tosca:Compute
```

And produces:

```
outputs:
    var:
      nodeTemplateName: node_1
      targetType: attribute
      target: tosca_id
```

This is done with the following code:
https://github.com/tliron/puccini/blob/f8c4d215ac1c75eb0645771425af60ff711909ad/tosca/grammars/tosca_v2_0/output-mapping.go#L55-L74

And the current implementation of mapping for the relationship almost duplicates the implementation for node:
https://github.com/tliron/puccini/blob/f8c4d215ac1c75eb0645771425af60ff711909ad/tosca/grammars/tosca_v2_0/output-mapping.go#L76-L94

It is not intuitive for me, how to get the requirement's `nodeTemplateName` or source node's name in this function context. Is this possible?

**Comment by tliron** [comment]
Actually, section [3.6.15] says more things -- that the mapping supporting nested attributes, ... more work will be necessary here.

**Comment by tliron** [comment]
The new commit has a solution. I would appreciate your feedback! Note that you have to `--coerce` to get the final TARGET name.

From the commit description:

> output mappings for operations and notifications now fully support TOSCA 1.3 section 3.6.15, with modelable entity names (SELF,
SOURCE, TARGET) and nested attributes. This works by making outputs into values, specifically a list of strings, a TOSCA path. If the entity is SOURCE or TARGET then the first element becomes a function call to the new internal _get_modelable_entity which will return the correct node template name.

**Comment by Shishqa** [comment]
Thank you for fast response!

I've checked your commit, but for me it still doesn't seem to be working:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

relationship_types:

  CustomDependsOn:
    derived_from: tosca.relationships.DependsOn
    valid_target_types:
      - tosca:Compute
    interfaces:
      Configure:
        operations:
          pre_configure_target:
            implementation: playbook.yaml
            outputs:
              ip: [ TARGET, public_address ]

topology_template:

  node_templates:

    server_2:
      type: tosca:Compute
      requirements:
        - dependency:
            node: server_1
            relationship:
              type: CustomDependsOn

    server_1:
      type: tosca:Compute
```
Here I want to set the target's ip address, for example. And puccini gives:
```
> puccini-tosca parse example.yaml 
PROBLEMS (1)
  file:/home/shishqa/dev/tmp/puccini/example.yaml
    @15,29 relationship_types["CustomDependsOn"].interfaces["Configure"].operations["pre_configure_target"].outputs["ip"][1]: unknown attribute reference in relationship "relationship": public_address
```

I assume, this happens because `self.setRelationship` still looks for attributes inside the relationship:
https://github.com/tliron/puccini/blob/f73035b66939a4b0a095df8e483963d2e7978e00/tosca/grammars/tosca_v2_0/output-mapping.go#L126-L134

**Comment by tliron** [comment]
You are correct, I shall fix!

**Comment by tliron** [comment]
OK, another fix. I think I figured it all out this time. :)

From the commit:

> We can now validate attributes against the relevant node and relationship types. Note, however, that we cannot validate the TARGET attributes, because the target node type is not known until the target node template is resolved. We at best know the base type only.

**Comment by Shishqa** [comment]
Thank you for the fixes!
Now it works good for me.

As far as I understand, the comment
https://github.com/tliron/puccini/blob/01a008b170190c3e94dbc8f3f91916a160edb0bb/tosca/grammars/tosca_v2_0/output-mapping.go#L22-L24
should be extended as well :)

**Comment by tliron** [comment]
Actually ... there is another issue I just noticed with validation. If the attribute is inside a capability it will error right now. One more fix!

**Comment by tliron** [comment]
For reference, you can see this bug with the following example:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

relationship_types:

  CustomDependsOn:
    derived_from: tosca.relationships.DependsOn
    valid_target_types:
      - tosca:Compute
    interfaces:
      Configure:
        operations:
          pre_configure_target:
            implementation: playbook.yaml
            outputs:
              ip: [ SOURCE, endpoint, ip_address ]

topology_template:

  node_templates:

    server_2:
      type: tosca:Compute
      requirements:
        - dependency:
            node: server_1
            relationship:
              type: CustomDependsOn

    server_1:
      type: tosca:Compute
```
