### ISSUE TITLE
Outputs are not rendered in relationship template operation

### ISSUE THREAD

**Issue by Shishqa** [tliron/puccini#132]
Consider an example:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
relationship_types:
  CustomDependsOn:
    derived_from: tosca.relationships.DependsOn
topology_template:
  node_templates:
    node_2:
      type: tosca:Root
      requirements:
        - dependency:
            node: node_1
            relationship: custom_depends
    node_1:
      type: tosca:Root
  relationship_templates:
    custom_depends:
      type: CustomDependsOn
      interfaces:
        Configure:
          operations:
            pre_configure_source:
              implementation: playbook.yaml
              outputs:
                var: [ TARGET, tosca_id ]
```

With running `puccini-tosca parse test.yaml` the puccini produces this output for the operation `pre_configure_source`:
```yaml
pre_configure_source:
    description: Operation to pre-configure the source endpoint.
    implementation: playbook.yaml
    dependencies: []
    inputs: {}
    outputs: {}
    timeout: -1
```

However, the expected output has to have outputs (`var`) rendered.
The same output is produced with `SELF` and `SOURCE` keywords.

---

Puccini version:
```bash
version=v0.21.0
revision=2a24a6c3467380001480d2de5c4570bb60e53fb8
timestamp=2023-03-23 23:14:55 MSK
arch=amd64
os=linux
compiler=gc
compiler-version=go1.20.1
```
