### ISSUE TITLE
Capability name from requirement assignment is not rendered

### ISSUE THREAD

**Issue by Shishqa** [tliron/puccini#134]
Consider an example:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

topology_template:

  node_templates:

    node_1:
      type: tosca:Root
      requirements:
        - dependency:
            node: node_2
            capability: feature

    node_2:
      type: tosca:Root
```

Here I explicitly point to a capability named feature and expect it to show up in the normalized output:
```yaml
requirements:
      - name: dependency
        capabilityTypeName: tosca::Node
        capabilityName: feature
```

However, I get the following output:
```yaml
requirements:
      - name: dependency
        capabilityTypeName: tosca::Node
        capabilityName: ""
```
