### ISSUE TITLE
Inconsistent `$map` representation

### ISSUE THREAD

**Issue by Shishqa** [tliron/puccini#136]
Consider a small template:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  inputs:
    test:
      type: map
      default: {}
      key_schema:
        type: string
      entry_schema:
        type: string
```

Let's parse it and dump to yaml:
```
> puccini-tosca parse test.yaml
description: ""
nodeTemplates: {}
groups: {}
policies: {}
inputs:
  test:
    $meta:
      type: map
      key:
        type: string
      value:
        type: string
    $map: []
outputs: {}
workflows: {}
substitution: null
metadata: {}
scriptletNamespace: {}
```

> Here we have `$map: []`

Let's compile it and dump:
```
properties:
  tosca:
    description: ""
    inputs:
      test:
        $map: null
        $meta:
          key:
            type: string
          type: map
          value:
            type: string
    metadata: {}
    outputs: {}
vertexes: {}
```

> Here we have `$map: null`

Let's parse and dump to json:
```
> puccini-tosca parse test.yaml -f json
{
  "description": "",
  "groups": {},
  "inputs": {
    "test": {
      "$map": null,
      "$meta": {
        "key": {
          "type": "string"
        },
        "type": "map",
        "value": {
          "type": "string"
        }
      }
    }
  },
  "metadata": {},
  "nodeTemplates": {},
  "outputs": {},
  "policies": {},
  "scriptletNamespace": {},
  "substitution": null,
  "workflows": {}
}
```

> Here `$map: null`

## Expected

I expect that `$map` is equal to an empty list `[]`, as I have provided a default value `{}`.
