### ISSUE TITLE
node_filter in requirments does not compile as expected

### ISSUE THREAD

**Issue by ksimk** [tliron/puccini#18]
Hi Tal, 

i´m trying to model a simple network, and let the compiler select the nodes with the matching security level property. 

when i compile and visualize the yaml code below, with ./puccini-tosca compile my_tests/my_simple_network.yaml |./puccini-js exec tosca.visualize > /tmp/my-app.html && xdg-open /tmp/my-app.htmlD, i get the following topology: 

secure_port: 
  binding: my_compute_1
  link: my_network_3   

I would expect the compiler to match the requirments in the node_filter, and get a topology with 
secure_port: 
  binding: my_compute_2
  link: my_network_4
 
is there something wrong with the way I declare the node_filter, or are there some compiler options to enable this kind of matching that I missed?

```
tosca_definitions_version: tosca_simple_yaml_1_0

description: Example of a simple Network with IEC62443 Security Properties

metadata:
  template_name: security_IEC62443
  template_author: kostyantyn_simkin


node_types:

# Secure Node Types

# Secure Network
  SecureNetwork:
    derived_from: tosca.nodes.network.Network
    properties:
      fr1_ac:
        type: integer
        default: 0
        constraints:
        - { in_range: [0,4] }

# Secure Port        
  SecurePort:
    derived_from: tosca.nodes.network.Port
    properties:
      fr1_ac:
        type: integer
        default: 0
        constraints:
        - { in_range: [0,4] }


        
  SecureCompute:
    derived_from: tosca.nodes.Compute
    properties:
      fr1_ac:
        type: integer
        default: 0
        constraints:
        - { in_range: [0,4] }


topology_template:
  
  node_templates:
    

    my_network_1:
      type: SecureNetwork
      properties:
        fr1_ac: 1
    
    my_network_2:
      type: SecureNetwork
      properties:
        fr1_ac: 2
    
    my_network_3:
      type: SecureNetwork
      properties:
        fr1_ac: 3
    
    my_network_4:
      type: SecureNetwork
      properties:
        fr1_ac: 4    
    
    my_compute_1:
      type: SecureCompute
      properties:
        fr1_ac: 1
    
    my_compute_2:
      type: SecureCompute
      properties:
        fr1_ac: 3
    
    my_secure_port:
      type: SecurePort
      requirements:
      - link:
          capability: tosca.capabilities.network.Linkable
          node: SecureNetwork
          node_filter:
            properties:
              fr1_ac:
              - greater_than: 3
      - binding: 
          capability: tosca.capabilities.network.Bindable
          node: SecureCompute
          node_filter:
            properties:
              fr1_ac:
              - greater_than: 2
      
      

```
