### ISSUE TITLE
Parse return wrong error information

### ISSUE THREAD

**Issue by huangsun** [tliron/puccini#33]
Hi
I run into the below error:

Parse two different file but getting same error return

temp1.yaml looks like:
```
tosca_definitions_version: tosca_simple_yaml_1_3
imports:
  - file: file_not_exist.yaml
  - file: file_exist.yaml
...
```
temp2.yaml looks like:
```
tosca_definitions_version: tosca_simple_yaml_1_3
imports:
  - file: file_exist.yaml
...
```

Parse temp1.yaml return:
```
phase 1: read
Problems (1)
  internal:temp1.yaml
    @4,5 imports[0]: URL not found: file_not_exist.yaml
    └─E:/xxx/github.com/tliron/puccini@v0.13.0/tosca/grammars/tosca_v1_3/import.go:83
```
Parse temp2.yaml return the same:
```
phase 1: read
Problems (1)
  internal:temp1.yaml
    @4,5 imports[0]: URL not found: file_not_exist.yaml
    └─E:/xxx/github.com/tliron/puccini@v0.13.0/tosca/grammars/tosca_v1_3/import.go:83
```

I think the problem is re-use self.Problems in
```
func (self *Context) NewImportContext(url urlpkg.URL) *Context {
	return &Context{
		Name:               self.Name,
		Path:               self.Path,
		URL:                url,
		CanonicalNamespace: self.CanonicalNamespace,
		Namespace:          make(Namespace),
		ScriptletNamespace: make(ScriptletNamespace),
		Hierarchy:          &Hierarchy{},
		Problems:           self.Problems,
		Quirks:             self.Quirks,
		Grammar:            self.Grammar,
	}
}
```

if changed to 
```
func (self *Context) NewImportContext(url urlpkg.URL) *Context {
	return &Context{
		Name:               self.Name,
		Path:               self.Path,
		URL:                url,
		CanonicalNamespace: self.CanonicalNamespace,
		Namespace:          make(Namespace),
		ScriptletNamespace: make(ScriptletNamespace),
		Hierarchy:          &Hierarchy{},
		Problems:           &problems.Problems{},
		Quirks:             self.Quirks,
		Grammar:            self.Grammar,
	}
}
```
every thing works fine to me,any suggestion here?

puccini version is v0.13.0

Thanks

**Comment by tliron** [comment]
Hi, I read this carefully and recreated the files as you stated, but I don't understand what the issue is. Perhaps you can provide a fuller example? E.g. I think you want the "file_exist.yaml" to actually exist, but I don't see it here. I'm just not sure exactly what you're trying to do.

Thank you for looking at the code, but actually it is important to share the Problems in the import context, because in the end you want to collect all problems from the parsed tree of units. Creating an independent Problems for the import means that you would never see those problems ...

**Comment by huangsun** [comment]
> Hi, I read this carefully and recreated the files as you stated, but I don't understand what the issue is. Perhaps you can provide a fuller example? E.g. I think you want the "file_exist.yaml" to actually exist, but I don't see it here. I'm just not sure exactly what you're trying to do.
> 
> Thank you for looking at the code, but actually it is important to share the Problems in the import context, because in the end you want to collect all problems from the parsed tree of units. Creating an independent Problems for the import means that you would never see those problems ...

Thank you for the reply, the complete example is:

file_exist.yaml:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

data_types:
  test_data:
    properties:
      id:
        type: string
        required: false
```

dep1.yaml:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - file: file_not_exist.yaml

  - file: file_exist.yaml

node_types:
  node1:
    properties:
      name:
        type: string
      data:
        type: test_data
        required: false

topology_template:
  inputs:
    name:
      type: string

  node_templates:
    node:
      type: node1
      properties:
        name: { get_input: name }
```

dep2.yaml:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - file: file_exist.yaml

node_types:
  node2:
    properties:
      name:
        type: string
      data:
        type: test_data
        required: false

topology_template:
  inputs:
    name:
      type: string

  node_templates:
    node:
      type: node2
      properties:
        name: { get_input: name }
```

tosca_test.go
```go
package main

import (
	cloutpkg "github.com/tliron/puccini/clout"
	"github.com/tliron/puccini/common"
	"github.com/tliron/puccini/tosca/compiler"
	"github.com/tliron/puccini/tosca/normal"
	"github.com/tliron/puccini/tosca/parser"
	problemspkg "github.com/tliron/puccini/tosca/problems"
	"testing"
)

func TestParse(t *testing.T) {
	common.ConfigureLogging(-1,nil)

	input:=make(map[string]interface{})
	input["name"]="test"

	testCompile(t, "dep1.yaml", input)
	testCompile(t, "dep2.yaml", input)
}

func testCompile(t *testing.T, url string, inputs map[string]interface{}) {
	var serviceTemplate *normal.ServiceTemplate
	var clout *cloutpkg.Clout
	var problems *problemspkg.Problems
	var err error

	if serviceTemplate, problems, err = parser.Parse(url, nil, inputs); err != nil {
		t.Errorf("%s\n%s", err.Error(), problems.ToString(true))
		return
	}

	if clout, err = compiler.Compile(serviceTemplate, true); err != nil {
		t.Errorf("%s\n%s", err.Error(), problems.ToString(true))
		return
	}

	compiler.Resolve(clout, problems, "yaml", false, true, true)
	if !problems.Empty() {
		t.Errorf("%s", problems.ToString(true))
		return
	}

	compiler.Coerce(clout, problems, "yaml", false, true, true)
	if !problems.Empty() {
		t.Errorf("%s", problems.ToString(true))
		return
	}
}


```

run TestParse and getting error:
```
=== RUN   TestParse10
--- FAIL: TestParse10 (0.02s)
    tosca_test.go:30: phase 1: read
        Problems (1)
          file:dep1.yaml
            @4,5 imports[0]: URL not found: file_not_exist.yaml
            └─E:github.com/tliron/puccini@v0.13.0/tosca/grammars/tosca_v1_3/import.go:83
    tosca_test.go:30: phase 1: read
        Problems (1)
          file:dep1.yaml
            @4,5 imports[0]: URL not found: file_not_exist.yaml
            └─E:github.com/tliron/puccini@v0.13.0/tosca/grammars/tosca_v1_3/import.go:83
FAIL
```

the question is testCompile dep2.yaml should return success?it's like i do something wrong and get it fixed,but still having the same error

Thanks
