### ISSUE TITLE
node_filter parse failure

### ISSUE THREAD

**Issue by pmjordan** [tliron/puccini#38]
I've just tested the fix for issue #34 using version=v0.15.0. The error has changed but the example 12 supplied in that issue still does not parse successfully. The new errors are:
@23,17 topology_template.node_templates["mysql_compute"].node_filter.capabilities{0}.properties["mem_size"]: "ard.map" instead of "ard.list"
    @22,17 topology_template.node_templates["mysql_compute"].node_filter.capabilities{0}.properties["num_cpus"]: "ard.map" instead of "ard.list"
    @26,17 topology_template.node_templates["mysql_compute"].node_filter.capabilities{1}.properties["architecture"]: "ard.map" instead of "ard.list"
    @28,17 topology_template.node_templates["mysql_compute"].node_filter.capabilities{1}.properties["distribution"]: "ard.string" instead of "ard.list"
    @27,17 topology_template.node_templates["mysql_compute"].node_filter.capabilities{1}.properties["type"]: "ard.string" instead of "ard.list"

**Comment by tliron** [comment]
The TOSCA spec is very inconsistent on the format of this, as it seems each example of node filter does it differently. But this is the notation that seems to make the most sense to me, and it allows you to specify multiple constraints per each property, which is the whole reason for using a list, and it is also consistent with how constraints are used elsewhere in TOSCA:
```
    mysql_compute:
      type: Compute
      node_filter:
        capabilities:
          - host:
              properties:
                num_cpus:
                - equal: 2
                mem_size:
                - greater_or_equal: 2 GB
          - os:
              properties:
                architecture:
                - equal: x86_64
                type:
                - equal: linux
                distribution:
                - equal: ubuntu
```
