### ISSUE TITLE
call_operation extended notation unsupported

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#65]
The following template:
```
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    node:
      type: tosca.nodes.Root # or any node type
  policies:
    - policy:
        type: tosca.policies.Root # or any policy type
        targets: [ node ]
        triggers:
          t_ok:
            event: an.event.type
            action:
              - call_operation: Standard.stop
          t_problem:
            event: an.event.type
            action:
              - call_operation:
                  operation: Standard.stop
                  inputs: {}
```
is not supported by Puccini 0.18.0:
```sh
$ puccini-tosca compile triggers_action_call_operation.yaml 
PROBLEMS (1)
  file:....../triggers_action_call_operation.yaml
    @18,17 topology_template.policies{0}.triggers["t_problem"].action[0].call_operation: "map" instead of "string"
$
```

The extended notation for `call_operation` seems to be unsupported by Puccini, doesn't it?
