### ISSUE TITLE
issues on trigger definition condition

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#66]
The following template:
```
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    node:
      type: tosca.nodes.Root # or any node type
  policies:
    - policy:
        type: tosca.policies.Root # or any policy type
        targets: [ node ]
        triggers:
          t1:
            event: event.type1
            condition:
              and:
                - state:
                    - equal: started
            action: []
          t2:
            event: event.type2
            condition:
              or:
                - state:
                    - equal: started
            action: []
          t3:
            event: event.type3
            condition:
              not:
                - state:
                    - equal: started
            action: []
          t4:
            event: event.type4
            condition:
              state:
                - equal: started
            action: []
```
is not supported by puccini 0.18.0:
```sh
$ puccini-tosca compile triggers_condition.yaml 
PROBLEMS (4)
  file:....../triggers_condition.yaml
    @14,15 topology_template.policies{0}.triggers["t1"].condition.and: unsupported field
    @21,15 topology_template.policies{0}.triggers["t2"].condition.or: unsupported field
    @28,15 topology_template.policies{0}.triggers["t3"].condition.not: unsupported field
    @35,15 topology_template.policies{0}.triggers["t4"].condition.state: unsupported field
$
```

These four condition clause definitions should be supported, shouldn't them?
