### ISSUE TITLE
constraints unchecked by 'puccini-tosca compile'

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#67]
Puccini should raise 2 problems on the following template:
```
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  MyNodeType:
    properties:
      p:
        type: integer
        constraints:
          - greater_or_equal: 0
        default: -100 # PROBLEM: not greater_or_equal: 0
topology_template:
  node_templates:
    node1:
      type: MyNodeType
    node2:
      type: MyNodeType
      properties:
        p: -200 # PROBLEM: not greater_or_equal: 0
```

But no problem is raised:
```sh
$ puccini-tosca compile previous_template.yaml 
version: "1.0"
metadata:
...
$
```

Are constraints checked? If yes, when are  constraints checked?
