### ISSUE TITLE
importing files containing topology_template unsupported

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#68]
Importing a file containing a topology template seems to be unsupported by Puccini 0.18.0.

Following is the importing template:
```
tosca_definitions_version: tosca_simple_yaml_1_3
imports:
  - imported_template.yaml
topology_template:
  node_templates:
    node1:
      type: tosca:Compute
```

Following is the imported template:
```
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    node2:
      type: tosca:Compute
```

A problem is signaled when compiling the importing template:
```sh
$ puccini-tosca compile importing_template.yaml 
PROBLEMS (1)
  file:........./imported_template.yaml
    @3,1 topology_template: unsupported field
$
```
