### ISSUE TITLE
two different behaviours on capability occurrences

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#69]
Puccuni 0.18.0 signals no problem on the following template:
```
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  MyNodeType:
    capabilities:
      cap:
        type: tosca:Compute
        # default occurrences is [1, UNBOUNDED]
#        occurrences: [1, UNBOUNDED]
topology_template:
  node_templates:
    node:
      type: MyNodeType
```

But if one uncomments `occurrences: [1, UNBOUNDED]` then Puccini signals a problem:
```sh
$ puccini-tosca compile previous_template.yaml 
PROBLEMS (1)
  Resolution
    @12,5 topology_template.node_templates["node"].capabilities["cap"]: not enough relationships: 0 < 1
$
```

This seems that there are two totally different behaviours depending on the absence or presence of the `occurrences` keyname. Moreover TOSCA 1.3 does not specify that each capability MUST BE the target of a relationship.
