### ISSUE TITLE
two different behaviours on requirement occurrences

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#73]
Puccuni 0.18.0 signals no problem on the following template:

```
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  MyNodeType:
    requirements:
      - req:
          capability: tosca:Compute
          # default occurrences is [1, 1]
#          occurrences: [1, 1]
topology_template:
  node_templates:
    node:
      type: MyNodeType
    compute:
      type: tosca:Compute
```

The `req` requirement of `node`template is fulfilled to the `compute` node template.

But if one uncomments `occurrences: [1, 1]` then Puccini signals a problem:

```sh
$ puccini-tosca compile previous_template.yaml 
PROBLEMS (1)
  file:.........../previous_template.yaml
    @11,5 topology_template.node_templates["node"].requirements: number of requirement "req" assignments is 0, must be >= 1 and <= 1
$
```
This seems that there are two totally different behaviours depending on the absence or presence of the `occurrences` keyname.
