### ISSUE TITLE
unknown requirement reference in node template

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#74]
Puccuni 0.18.0 signals no problem on the following template:

```
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  MyNodeType:
    requirements:
      - req:
          capability: tosca:Compute
          # default occurrences is [1, 1]
#          occurrences: [1, 1]
topology_template:
  substitution_mappings:
    node_type: MyNodeType
    requirements:
      req: [ node, req ]
  node_templates:
    node:
      type: MyNodeType
```

But if one uncomments `occurrences: [1, 1]` then Puccini signals two problems:

```sh
$ puccini-tosca compile previous_template.yaml
PROBLEMS (2)
  file:......./previous_template.yaml
    @16,5 topology_template.node_templates["node"].requirements: number of requirement "req" assignments is 0, must be >= 1 and <= 1
    @14,20 topology_template.substitution_mappings.requirements["req"][1]: unknown requirement reference in node template "node": req
$
```

The first problem is already reported in https://github.com/tliron/puccini/issues/73.
The second problem illustrates that there are two totally different behaviours depending on the absence or presence of the `occurrences` keyname.
