### ISSUE TITLE
PropertyMapping is not accepting simple values

### ISSUE THREAD

**Issue by jpc4242** [tliron/puccini#75]
Originally discussed in #59 
A property mapping that is a single value is currently rejected:
```yaml
topology_template:
  substitution_mappings:
    node_type: mynode
    properties:
      flavour_id: simple
```
yields `topology_template.substitution_mappings.properties["flavour_id"]: "string" instead of "list" error`

But for tosca up to 1.2 (included) this should be accepted
For tosca 1.3 and later property mappings involving a constant are discontinued so puccini is already behaving correctly
