### ISSUE TITLE
in_range constraint

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#86]
Puccini compiles well the following service template:
```
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  MyNodeType:
    derived_from: tosca.nodes.Root
    properties:
      port_range:
        type: range
#        constraints:
#          - in_range: [0, 65535]
policy_types:
  MyPolicyType:
    derived_from: tosca.policies.Root
    properties:
      port_range:
        type: range
#        constraints:
#          - in_range: [0, 65535]
topology_template:
  node_templates:
    node1:
      type: MyNodeType
      properties:
        port_range: [1000, 5000]
  policies:
    - policy1:
        type: MyPolicyType
        properties:
          port_range: [1000, 5000]
```

But when uncommenting the in_range constraints then puccini produces following problems:
```sh
$ puccini-tosca compile in_range.yaml 
PROBLEMS (4)
  file:.../in_range.yaml
    @23,22 topology_template.node_templates["node1"].properties["port_range"][0]: "integer" instead of "list"
    @23,28 topology_template.node_templates["node1"].properties["port_range"][1]: "integer" instead of "list"
    @28,24 topology_template.policies{0}.properties["port_range"][0]: "integer" instead of "list"
    @28,30 topology_template.policies{0}.properties["port_range"][1]: "integer" instead of "list"
```
Is it normal? or are false problems?
