### ISSUE TITLE
"string" instead of "list"

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#87]
Puccini produces a problem on the following service template (a simplified version of an ETSI NFV SOL001 example):
```
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  VNF:
    derived_from: tosca.nodes.Root
    properties:
      vnfm_info:
        type: list
        required: true
        entry_schema:
          type: string
  MyVNF:
    derived_from: VNF
    properties:
      vnfm_info:
        type: list
        entry_schema:
          type: string
        constraints: [ equal: [ '0:MyCompany-1.0.0' ] ]
topology_template:
  node_templates:
    node1:
      type: MyVNF
      properties:
        vnfm_info:
          - '0:MyCompany-1.0.0'
```
```sh
$ puccini-tosca compile --quirk etsinfv vnfm_info.yaml 
PROBLEMS (1)
  file:.../vnfm_info.yaml
    @25,13 topology_template.node_templates["node1"].properties["vnfm_info"][0]: "string" instead of "list"
```
When commenting the `constraints: [ equal: [ '0:MyCompany-1.0.0' ] ]` line, the problem disappears.

Why does the `constraints: [ equal: [ '0:MyCompany-1.0.0' ] ]` line introduce the problem?
