### ISSUE TITLE
Parameter refinements not supported in capability type defintions

### ISSUE THREAD

**Issue by pmjordan** [tliron/puccini#98]
My TOSCA template contains
``` YAML
tosca_defintions_version: tosca_simple_yaml_1_3
capability_types:
  TMFAPI:
    derived_from: tosca.capabilities.Node
    description: a TMForum defined REST API
      properties:
        id:
          type: string
          description: the id e.g TMF632
        name
          type: string
          description: the name, e.g. party

  TMF632:
     derived_from: TMFAPI
     properties:
       id: TMF632
       name: party
```
But this is rejected the puccini parser with a message 
@19, 7 capability_types["TMF632"].properties["id"]: "string" instead of "map"
@20, 7 capability_types["TMF632"].properties["name"]: "string" instead of "map"

Perhaps this is because you are not expecting property defintion refinements as described in section 3.6.10.6 of TOSCA v1.3

thanks to @philippemerle for pointing out that an example of this syntax is given in section 3.6.10.8
